---
title: "Dimensionality reduction using SingleCellExperiment"
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(SingleCellExperiment)
library(scran)
library(scater)
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
source("/Users/ricard/10x_gastrulation_DNMTs/settings.R")
io$outdir <- paste0(io$basedir,"/results/dimensionality_reduction")
```

Define options
```{r}
opts$batches <- c(
  # E12.5  
  # "E125_DNMT3A_HET_A_L001",
  # "E125_DNMT3A_HET_A_L003",
  # "E125_DNMT3A_KO_B_L002",
  # "E125_DNMT3A_KO_E_L004",
  # "A_E12_5_D3a_Het_L001",
  # "B_E12_5_D3a_KO_L002",
  
  
  # E8.5  
  # "SIGAA6_E85_2_Dnmt3aKO_Dnmt3b_WT_L001",
  # "SIGAB6_E85_3_Dnmt3aWT_Dnmt3b_WT_L002",
  # "SIGAC6_E85_5_Dnmt3aKO_Dnmt3b_Het_L003",
  # "SIGAD6_E85_8_Dnmt3aHet_Dnmt3b_KO_L004",
  # "15_E8_5_D3A_WT_D3B_WT_L007"
  # "17_E8_5_D3A_KO_D3B_WT_L008",
  "2_E8_5_D3A_WT_D3B_KO_L003"
  # "3_E8_5_D3A_HET_D3B_WT_L004",
  # "7_E8_5_D3A_WT_D3B_KO_L005",
  # "8_E8_5_D3A_KO_D3B_KO_L006",
  # "E8_5_Dnmt1_KO_male_SIGAC8_L001",
  # "E8_5_Dnmt1_KO_male_SIGAD8_L002"
  # "E8_5_Dnmt1_KO_male_SIGAE8_L003",
  # "E8_5_Dnmt1_WT_female_SIGAB8_L004",
  # "E8_5_Dnmt1_WT_female_SIGAF8_L005",
  # "E8_5_Dnmt3ab_WT_female_SIGAA8_L006",
  # "SIGAH10_Dnmt3ab_WT_L002"
  # "SIGAH11_Dnmt3ab_WT_L003",
  # "SIGAH9_Dnmt3a_KO_Dnmt3b_Het_L001"
)
```

Update sample metadata
```{r load_metadata, echo=FALSE}
sample_metadata <- fread(io$metadata) %>%
  .[pass_QC==TRUE & batch%in%opts$batches]
table(sample_metadata$batch)
```

```{r}
table(sample_metadata$celltype.mapped)
```

# Load data

Load RNA expression data as SingleCellExperiment object
```{r load_data, echo=FALSE}
sce <- readRDS(io$sce)[,sample_metadata$cell]
dim(sce)
```

```{r}
sce$celltype.mapped <- sample_metadata$celltype.mapped
```

Change gene names from ENSEMBL to symbols
```{r}
# gene_metadata <- fread(io$gene_metadata) %>% .[,c("ens_id","symbol")] %>%
#   .[symbol!="" & ens_id%in%rownames(sce)] %>%
#   .[!duplicated(symbol)]
# 
# sce <- sce[rownames(sce)%in%gene_metadata$ens_id,]
# foo <- gene_metadata$symbol; names(foo) <- gene_metadata$ens_id
# new.names <- foo[rownames(sce)]
# 
# # Sanity cehcks
# stopifnot(sum(is.na(new.names))==0)
# stopifnot(sum(duplicated(new.names))==0)
# 
# # Set names
# rownames(sce) <- new.names
```

# Parse data

Select HVG
```{r}
decomp <- modelGeneVar(sce)
decomp <- decomp[decomp$mean > 0.01,]
hvgs <- rownames(decomp)[decomp$p.value <= 0.05]

# Subset SingleCellExperiment
sce_filt <- sce[hvgs,]
dim(sce_filt)
```

Use gene markers as HVGs
```{r}
# io$atlas.marker_genes <- "/Users/ricard/data/gastrulation10x/results/marker_genes/E8.5/marker_genes.txt.gz"
# 
# marker_genes.dt <- fread(io$atlas.marker_genes)
# marker_genes.dt <- marker_genes.dt[,head(.SD,n=50),by="celltype"]
# marker_genes <- unique(marker_genes.dt$gene)
# marker_genes <- marker_genes[marker_genes%in%rownames(sce)]
# length(marker_genes)
```

```{r}
data <- scale(t(logcounts(sce_filt)), center = T, scale = F)
```

Regress out covariates (this is very slow...)
```{r}
# data <- apply(data, 2, function(x) {
#   lm(formula=expr~covariate, data=data.frame(expr=x, covariate=factor(sce_filt$nFeature_RNA)))[["residuals"]]
# })
```


# PCA

Run PCA
```{r}
npcs <- 25
reducedDim(sce_filt, "PCA") <- irlba::prcomp_irlba(data, n=npcs)$x[,1:npcs]
```

```{r}
cor(sce_filt$nFeature_RNA, reducedDim(sce_filt,"PCA"))
```

Plot PCA
```{r}
# plotPCA(sce_filt, colour_by="celltype.mapped", ncomponents = c(1,3)) +
#   scale_color_manual(values=opts$celltype.colors) +
#   theme(
#     legend.position = "none"
#   )
```
Filter PCS
```{r}
reducedDim(sce_filt, "PCA") <- reducedDim(sce_filt, "PCA")[,-3]
```

# UMAP

Run UMAP
```{r}
set.seed(42)
# sce_filt <- runUMAP(sce_filt, dimred="PCA")
sce_filt <- runUMAP(sce_filt, dimred="PCA", n_neighbors = 30, min_dist = 0.3)
reducedDim(sce, "UMAP") <- reducedDim(sce_filt, "UMAP") 
```

Plot UMAP

```{r}
to.plot <- reducedDim(sce_filt,"UMAP") %>% as.data.table %>% 
  .[,cell:=colnames(sce_filt)] %>%
    merge(sample_metadata, by="cell")
```

```{r}
p <- ggplot(to.plot, aes(x=V1, y=V2, fill=celltype.mapped)) +
  geom_point(size=2.5, shape=21, stroke=0.1) +
  # scale_color_manual(values=opts$stage.colors) +
  scale_fill_manual(values=opts$celltype.colors) +
  theme_classic() +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position="none",
    legend.title=element_blank()
  )

# pdf(paste0(io$outdir,"/rna_umap.pdf"), width=5, height=3, useDingbats = F)
print(p)
# dev.off()
```

```{r}
plotUMAP(sce, colour_by="Cldn3")
```

```{r}
doublets.dt <- fread("/Users/ricard/data/10x_gastrulation_DNMTs/results/doublets/doublets.txt.gz") %>%
  .[batch%in%opts$batches]
to.plot <- to.plot %>% merge(doublets.dt,by=c("cell","batch"))
colnames(to.plot)
```

```{r}
to.plot$hybrid_score <- as.numeric(to.plot$hybrid_score)
to.plot$bcds_score <- as.numeric(to.plot$bcds_score)
```

```{r}
ggplot(to.plot, aes(x=V1, y=V2, fill=bcds_score)) +
  geom_point(size=1.5, shape=21, stroke=0.2) +
	viridis::scale_fill_viridis() +
  theme_classic() +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.title=element_blank()
  )
```

```{r}
print(object.size(sce@assays@data$counts), units="auto")
print(object.size(sce@assays@data$logcounts), units="auto")
class(sce@assays@data$counts)
class(sce@assays@data$logcounts)

sce <- logNormCounts(sce)
altExp(sce)
assays(sce)

sce@assays@data$logcounts <- NULL
```

