---
title: "Pluripotency score"
---
  
```{r load_modules, echo=FALSE, include=FALSE}
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
source("/Users/ricard/10x_gastrulation_DNMTs/settings.R")
io$outdir <- paste0(io$basedir,"/results/pluripotency_score")
```

Define options
```{r}
opts$batches <- c(
  "SIGAA6_E85_2_Dnmt3aKO_Dnmt3b_WT_L001",
  "SIGAB6_E85_3_Dnmt3aWT_Dnmt3b_WT_L002",
  "SIGAC6_E85_5_Dnmt3aKO_Dnmt3b_Het_L003",
  "SIGAD6_E85_8_Dnmt3aHet_Dnmt3b_KO_L004",
  "15_E8_5_D3A_WT_D3B_WT_L007",
  "17_E8_5_D3A_KO_D3B_WT_L008",
  "2_E8_5_D3A_WT_D3B_KO_L003",
  "3_E8_5_D3A_HET_D3B_WT_L004",
  "7_E8_5_D3A_WT_D3B_KO_L005",
  "8_E8_5_D3A_KO_D3B_KO_L006"
)

# opts$pluripotency_genes
# opts$pluripotency_genes <- fread("/Users/ricard/data/gastrulation/rna/results/differential/E4.5Epiblast_vs_E7.5EctodermEndodermMesoderm.txt.gz") %>% .[padj_fdr<=0.01 & logFC<(-3),symbol]
```

Update sample metadata
```{r load_metadata, echo=FALSE}
sample_metadata <- sample_metadata %>%
  .[batch%in%opts$batches]
table(sample_metadata$batch)
```

# Load data

Load RNA expression data as SingleCellExperiment object
```{r load_data, echo=FALSE}
sce <- readRDS(io$sce)[,sample_metadata$cell]
dim(sce)
```

Normalise
```{r}
## Normalisation
sce <- batchelor::multiBatchNorm(sce, batch=as.factor(sce$batch))
# sce <- scater::logNormCounts(sce)
```

Change gene names from ENSEMBL to symbols
```{r}
gene_metadata <- fread(io$gene_metadata) %>% .[,c("ens_id","symbol")] %>%
  .[symbol!="" & ens_id%in%rownames(sce)]

gene_metadata$symbol[duplicated(gene_metadata$symbol)]

sce <- sce[rownames(sce)%in%gene_metadata$ens_id,]
foo <- gene_metadata$symbol; names(foo) <- gene_metadata$ens_id
new.names <- foo[rownames(sce)]

# Sanity cehcks
stopifnot(sum(is.na(new.names))==0)
stopifnot(sum(duplicated(new.names))==0)

# Set names
rownames(sce) <- new.names
```

# Calculate pluripotency scores

```{r}
opts$pluripotency_genes <- opts$pluripotency_genes[opts$pluripotency_genes%in%rownames(sce)]
```

```{r}
sce.filt <- sce[opts$pluripotency_genes,]
```

```{r}
to.plot <- data.table(
  cell = colnames(sce.filt),
  pluripotency_score = colMeans(logcounts(sce.filt))
) %>% merge(sample_metadata,by="cell")
```

# Plot

```{r}
p <- ggplot(to.plot, aes(x=batch, y=pluripotency_score, fill=batch)) +
  # geom_jitter(size=0.8) +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.5, outlier.shape=NA) +
  # scale_fill_manual(values=opts$celltype.colors) +
  facet_wrap(~celltype.mapped) +
  theme_classic() +
  labs(x="",y="RNA expression") +
  theme(
    # axis.text.x = element_text(colour="black",size=rel(1.0), angle=50, hjust=1),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour="black",size=rel(1.0)),
    legend.position="none",
    legend.title=element_blank()
  )
  
# pdf(sprintf("%s/%s.pdf",io$outdir,i), width=8, height=3.5, useDingbats = F)
# ggsave("ggtest.png", width = 3.25, height = 3.25, dpi = 1200)
# jpeg(sprintf("%s/%s.jpeg",io$outdir,gene), width = 1500, height = 600)
print(p)
# dev.off()
```

