samples:
    # E125_DNMT3A_HET_A_L001: E125_DNMT3A_HET_A_L001
    # E125_DNMT3A_HET_A_L003: E125_DNMT3A_HET_A_L003
    # E125_DNMT3A_KO_B_L002: E125_DNMT3A_KO_B_L002
    # E125_DNMT3A_KO_E_L004: E125_DNMT3A_KO_E_L004
    SIGAA6_E85_2_Dnmt3aKO_Dnmt3b_WT_L001: SIGAA6_E85_2_Dnmt3aKO_Dnmt3b_WT_L001
    SIGAB6_E85_3_Dnmt3aWT_Dnmt3b_WT_L002: SIGAB6_E85_3_Dnmt3aWT_Dnmt3b_WT_L002
    SIGAC6_E85_5_Dnmt3aKO_Dnmt3b_Het_L003: SIGAC6_E85_5_Dnmt3aKO_Dnmt3b_Het_L003
    SIGAD6_E85_8_Dnmt3aHet_Dnmt3b_KO_L004: SIGAD6_E85_8_Dnmt3aHet_Dnmt3b_KO_L004
    15_E8_5_D3A_WT_D3B_WT_L007: 15_E8_5_D3A_WT_D3B_WT_L007
    17_E8_5_D3A_KO_D3B_WT_L008: 17_E8_5_D3A_KO_D3B_WT_L008
    2_E8_5_D3A_WT_D3B_KO_L003: 2_E8_5_D3A_WT_D3B_KO_L003
    3_E8_5_D3A_HET_D3B_WT_L004: 3_E8_5_D3A_HET_D3B_WT_L004
    7_E8_5_D3A_WT_D3B_KO_L005: 7_E8_5_D3A_WT_D3B_KO_L005
    8_E8_5_D3A_KO_D3B_KO_L006: 8_E8_5_D3A_KO_D3B_KO_L006
    # A_E12_5_D3a_Het_L001: A_E12_5_D3a_Het_L001
    # B_E12_5_D3a_KO_L002: B_E12_5_D3a_KO_L002
    E8_5_Dnmt1_KO_male_SIGAC8_L001: E8_5_Dnmt1_KO_male_SIGAC8_L001
    E8_5_Dnmt1_KO_male_SIGAD8_L002: E8_5_Dnmt1_KO_male_SIGAD8_L002
    E8_5_Dnmt1_KO_male_SIGAE8_L003: E8_5_Dnmt1_KO_male_SIGAE8_L003
    E8_5_Dnmt1_WT_female_SIGAB8_L004: E8_5_Dnmt1_WT_female_SIGAB8_L004
    E8_5_Dnmt1_WT_female_SIGAF8_L005: E8_5_Dnmt1_WT_female_SIGAF8_L005
    E8_5_Dnmt3ab_WT_female_SIGAA8_L006: E8_5_Dnmt3ab_WT_female_SIGAA8_L006
    SIGAH10_Dnmt3ab_WT_L002: SIGAH10_Dnmt3ab_WT_L002
    SIGAH11_Dnmt3ab_WT_L003: SIGAH11_Dnmt3ab_WT_L003
    SIGAH9_Dnmt3a_KO_Dnmt3b_Het_L001: SIGAH9_Dnmt3a_KO_Dnmt3b_Het_L001
    SIGAG5_9_dnmt3ab_DKO_L005: SIGAG5_9_dnmt3ab_DKO_L005

# Cluster
# directories:
#     base: /hps/nobackup2/research/stegle/users/ricard/10x_gastrulation_DNMTs
#     original_data: /hps/nobackup2/research/stegle/users/ricard/10x_gastrulation_DNMTs/original/all_batches
#     processed_data: /hps/nobackup2/research/stegle/users/ricard/10x_gastrulation_DNMTs/processed/all_batches/test
#     results: /hps/nobackup2/research/stegle/users/ricard/10x_gastrulation_DNMTs/results
#     atlas: /hps/nobackup2/research/stegle/users/ricard/gasrulation10x


# scripts:
#     create_seurat: /homes/ricard/10x_gastrulation_DNMTs/processing/1_create_seurat.R
#     qc: /homes/ricard/10x_gastrulation_DNMTs/processing/2_QC.R
#     seurat_to_sce: /homes/ricard/10x_gastrulation_DNMTs/processing/3_seurat_to_SCE.R
#     mapping: /homes/ricard/10x_gastrulation_DNMTs/mapping/run/mnn/mapping_mnn.R

# Local computer
directories:
    base: /Users/ricard/data/10x_gastrulation_DNMTs
    original_data: /Users/ricard/data/10x_gastrulation_DNMTs/original/all_batches
    processed_data: /Users/ricard/data/10x_gastrulation_DNMTs/processed/all_batches/test
    results: /Users/ricard/data/10x_gastrulation_DNMTs/results
    atlas: /Users/ricard/data/gastrulation10x

scripts:
    create_seurat: /Users/ricard/10x_gastrulation_DNMTs/processing/1_create_seurat.R
    qc: /Users/ricard/10x_gastrulation_DNMTs/processing/2_QC.R
    seurat_to_sce: /Users/ricard/10x_gastrulation_DNMTs/processing/3_seurat_to_SCE.R
    mapping: /Users/ricard/10x_gastrulation_DNMTs/mapping/run/mnn/mapping_mnn.R


lsf:
    create_seurat:
        memory:
            20000