---
title: "X chromosome inactivation"
---

```{r echo=FALSE, include=FALSE}
library(scater)
library(ggpubr)
```

```{r define_opts, echo=FALSE, include=FALSE}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/10x_gastrulation_DNMTs/settings.R")
  source("/Users/ricard/10x_gastrulation_DNMTs/utils.R")
} else {
  stop("Computer not recognised")
}
io$outdir <- paste0(io$basedir,"/results/chrX_inactivation")
```

Define options
```{r}
opts$classes <- c(
  "E8.5_WT",
  "E8.5_Dnmt3aKO_Dnmt3bWT",
  "E8.5_Dnmt3aHET_Dnmt3bKO",
  # "E8.5_Dnmt3aHET_Dnmt3bWT",
  # "E8.5_Dnmt3aKO_Dnmt3bHET",
  "E8.5_Dnmt3aWT_Dnmt3bKO",
  "E8.5_Dnmt3aKO_Dnmt3bKO",
  "E8.5_Dnmt1KO"
)

```

Load sample metadata
```{r}
sample_metadata <- fread(io$metadata) %>%
  .[pass_QC==TRUE & class%in%opts$classes & sex=="female"]
```

# Load data

Load SingleCellExperiment
```{r load_expr, echo=FALSE, include=FALSE}
sce <- load_SingleCellExperiment(io$sce, cells=sample_metadata$cell, normalise = TRUE, remove_non_expressed_genes = TRUE)

# Add sample metadata as colData
colData(sce) <- sample_metadata %>% tibble::column_to_rownames("cell") %>% DataFrame

dim(sce)
```


Load gene metadata
```{r}
gene_metadata <- fread(io$gene_metadata) %>%
  setnames("symbol","gene") %>%
  .[gene%in%rownames(sce)]
```

# Parse data

Group genes by chromosome
```{r}
genes.chrY <- gene_metadata[chr=="chrY",gene]
genes.chrX <- gene_metadata[chr=="chrX",gene]
genes.chr10 <- gene_metadata[chr=="chr10",gene]
```

Create data.table from SingleCellExperiment object
```{r}
dt <- counts(sce[c(genes.chrX,genes.chr10),]) %>% as.matrix %>% t %>%
  as.data.table(keep.rownames="cell") %>%
  melt(id.vars="cell", value.name="counts", variable.name="gene") %>%
  merge(sample_metadata[,c("cell","sample","class","celltype.mapped")], by="cell") # %>%
  merge(gene_metadata[,c("chr","gene")], by="gene")
```

```{r}
# dt <- opts$samplees %>% map(function(i) { 
#   sce.filt <- sce[,sce$sample==i] %>% .[c(genes.chrY,genes.chrX,genes.chr10),]
#   dt <- data.table(
#     ens_id = rownames(sce.filt),
#     counts = counts(sce.filt) %>% Matrix::rowSums()
#   ) %>% .[,sample:=i] %>% merge(sample_metadata[,c("cell","celltype.mapped")],by=c("cell","sample"))
# }) %>% rbindlist %>% merge(gene_metadata[,c("chr","ens_id","symbol")], by="ens_id")
```

# Plot

## Xist expression per embryo and lineage

```{r}
to.plot <- dt %>% .[gene%in%"Xist"] %>%
  .[,.(counts=mean(counts)),by=c("sample","class","gene","celltype.mapped")]
```

```{r}
p <- ggbarplot(to.plot, x="celltype.mapped", y="counts", fill="celltype.mapped") +
  facet_wrap(~sample) +
  scale_fill_manual(values=opts$celltype.colors) +
  labs(x="", y="Average Xist counts") +
  theme(
    legend.position = "none",
    # axis.text.x = element_text(colour="black",size=rel(0.8), angle=45, hjust=1, vjust=1),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# pdf(sprintf("%s/pdf/sex_ychr_expr_aggregated.pdf",io$outdir), width=8, height=6, useDingbats = F)
print(p)
# dev.off()
```

```{r}
p <- ggboxplot(to.plot, x="celltype.mapped", y="counts", fill="celltype.mapped") +
  facet_wrap(~class) +
  scale_fill_manual(values=opts$celltype.colors) +
  labs(x="", y="Average Xist counts") +
  theme(
    legend.position = "none",
    # axis.text.x = element_text(colour="black",size=rel(0.8), angle=45, hjust=1, vjust=1),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# pdf(sprintf("%s/pdf/sex_ychr_expr_aggregated.pdf",io$outdir), width=8, height=6, useDingbats = F)
print(p)
# dev.off()
```

## Plot chrX/chr10 ratio per embryo and lineage

```{r}
to.plot <- dt %>% 
  .[,.(counts=sum(counts)),by=c("sample","chr","celltype.mapped")] %>%
  dcast(sample+celltype.mapped~chr, value.var="counts") %>%
  .[,ratioX:=chrX/chr10]
```

Barplots of chrX/chr10 count ratio per sample and lineage
```{r}
p <- ggbarplot(to.plot, x="celltype.mapped", y="ratioX", fill="celltype.mapped") +
  facet_wrap(~sample) +
  scale_fill_manual(values=opts$celltype.colors) +
  labs(x="", y="chrX/chr10 counts ratio") +
  theme(
    legend.position = "none",
    # axis.text.x = element_text(colour="black",size=rel(0.8), angle=45, hjust=1, vjust=1),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# pdf(sprintf("%s/pdf/sex_ychr_expr_aggregated.pdf",io$outdir), width=8, height=6, useDingbats = F)
print(p)
# dev.off()
```


## Explore

```{r}
to.plot <- dt %>%
  .[,.(counts=mean(counts)),by=c("sample","class","gene","chr")]
```

Imprinting
```{r}
imprinted_genes.dt <- fread("/Users/ricard/data/mm10_regulation/imprinting/parsed/geneimprint_imprinted_genes.txt.gz")
```

```{r}
to.plot2 <- to.plot[grep("Rhox",gene)]

p <- ggboxplot(to.plot2, x="class", y="counts") +
  facet_wrap(~gene, scales="free_y") +
  labs(x="", y="Average counts") +
  theme(
    legend.position = "none",
    # axis.text.x = element_text(colour="black",size=rel(0.8), angle=45, hjust=1, vjust=1),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# pdf(sprintf("%s/pdf/sex_ychr_expr_aggregated.pdf",io$outdir), width=8, height=6, useDingbats = F)
print(p)
# dev.off()
```


